#!/usr/bin/env node

const fs = require('fs');
const https = require('https');

// Check if yahoo-finance2 is installed
let yahooFinance;
try {
  const YahooFinanceModule = require('yahoo-finance2').default || require('yahoo-finance2');
  // Try to instantiate or use directly
  yahooFinance = typeof YahooFinanceModule === 'function' ? new YahooFinanceModule({ suppressNotices: ['yahooSurvey', 'ripHistorical'] }) : YahooFinanceModule;
} catch (err) {
  console.error('ERROR: Failed to load yahoo-finance2');
  console.error(`  ${err.message}`);
  console.error('Make sure it\'s installed: npm install yahoo-finance2');
  process.exit(1);
}

const { renderProfile } = require('./templates/profile');
const { renderTheme, themeSlug } = require('./templates/theme');
const { renderCalendar } = require('./templates/calendar');
const { NAV_CSS, renderNav, renderFooterLinks } = require('./templates/site');
const { renderHomeHead, renderStaticStocks, renderStaticNews } = require('./templates/home');

const SITE = JSON.parse(fs.readFileSync('data/site.json', 'utf8'));

// Stock list, names and themes. A stock with data/profiles/<ticker>.json gets editorial
// sections on its page ("covered"); without one it gets a data-only page ("tracked").
const UNIVERSE = JSON.parse(fs.readFileSync('data/universe.json', 'utf8'));
const STOCKS = UNIVERSE.stocks.map(s => s.symbol);
const STOCK_INFO = Object.fromEntries(UNIVERSE.stocks.map(s => [s.symbol, s]));

// Retry transient Yahoo failures (rate limits, HTML error pages) with a short backoff
async function withRetry(fn, attempts = 3, delayMs = 1500) {
  for (let i = 1; ; i++) {
    try {
      return await fn();
    } catch (err) {
      if (i >= attempts) throw err;
      await new Promise(resolve => setTimeout(resolve, delayMs * i));
    }
  }
}

const MARKET_FILE = 'data/market.json';
const PROFILE_DIR = 'data/profiles';
const PAGES_DIR = 'stocks';
const THEME_DIR = 'data/themes';
const THEME_PAGES_DIR = 'themes';
const GENERATED_MARKER = '<!-- Generated by update-stocks.js';

// Fetch historical data from Yahoo Finance
async function getHistoricalData(symbol, startDate) {
  try {
    const endDate = new Date();
    const quotes = await withRetry(() => yahooFinance.historical(symbol, {
      period1: startDate,
      period2: endDate,
      interval: '1d'
    }));

    if (quotes && quotes.length > 0) {
      console.log(`    ✓ Got ${quotes.length} days of historical data for ${symbol}`);
      return quotes;
    } else {
      console.warn(`    ⚠️  No historical data for ${symbol}`);
      return null;
    }
  } catch (err) {
    console.warn(`    ⚠️  Error fetching historical data for ${symbol}: ${err.message}`);
    return null;
  }
}

// Fetch raw HTTP response (for RSS/HTML parsing)
function fetchRaw(url) {
  return new Promise((resolve, reject) => {
    const follow = (u) => {
      const mod = u.startsWith('https') ? require('https') : require('http');
      mod.get(u, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return follow(res.headers.location);
        }
        let data = '';
        res.on('data', (chunk) => { data += chunk; });
        res.on('end', () => resolve(data));
      }).on('error', reject);
    };
    follow(url);
  });
}

// Fetch news from Yahoo Finance using yahoo-finance2
async function getYahooNews(symbol) {
  try {
    const quote = await yahooFinance.quote(symbol);

    if (quote.news && Array.isArray(quote.news)) {
      return quote.news.slice(0, 3).map(item => ({
        title: item.title,
        source: item.publisher || 'Yahoo Finance',
        date: new Date(item.providerPublishTime * 1000).toISOString(),
        summary: item.summary || 'Financial news',
        url: item.link
      }));
    }
    return [];
  } catch (err) {
    // Silently fail, we'll use Google News
    return [];
  }
}

// Fetch news from Google News RSS
async function getGoogleNews(company) {
  try {
    const query = encodeURIComponent(`${company} stock`);
    const url = `https://news.google.com/rss/search?q=${query}&hl=en-US&gl=US&ceid=US:en`;
    const xml = await fetchRaw(url);
    const items = [];
    const itemRegex = /<item>([\s\S]*?)<\/item>/g;
    let match;

    // Collect extra candidates so there are still enough after low-value items are filtered out
    while ((match = itemRegex.exec(xml)) !== null && items.length < 12) {
      const item = match[1];
      const title = (item.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) || item.match(/<title>(.*?)<\/title>/))?.[1] || '';
      const link = (item.match(/<link>(.*?)<\/link>/) || [])[1] || '#';
      const pubDate = (item.match(/<pubDate>(.*?)<\/pubDate>/) || [])[1] || '';
      const source = (item.match(/<source[^>]*>(.*?)<\/source>/) || [])[1] || 'Google News';
      const date = pubDate ? new Date(pubDate).toISOString() : new Date().toISOString();

      if (title && link !== '#') {
        items.push({ title, source, date, summary: `Latest news about ${company}.`, url: link });
      }
    }

    return items;
  } catch (err) {
    return [];
  }
}

// Headlines that aren't news: law-firm lawsuit solicitations, quote pages, and
// auto-generated "should you sell?" filler
const LOW_VALUE_NEWS = [
  /stock price,? news,? quote/i,
  /\b(Levi (&amp;|&) Korsinsky|Rosen Law|Pomerantz|Bragar Eagel|Faruqi|Bronstein, Gewirtz|Glancy Prongay|Kessler Topaz|Schall Law|Gross Law|Portnoy Law|Robbins Geller|Kirby McInerney|Johnson Fistel)\b/i,
  /\b(class action|investor alert|shareholder alert|securities fraud|investigation on behalf)\b/i,
  /\bDEADLINE\b/,
  /\bShould You (Buy|Sell)\b/i,
  /\b(Resistance|Support) Level\b/i,
  /\bstock (forecast|prediction)\b/i
];

const isLowValueNews = (item) => LOW_VALUE_NEWS.some(re => re.test(item.title));

// Headlines that usually mean a profile's analysis needs updating: trial readouts,
// regulatory decisions, financings, deals and leadership changes
const MATERIAL_NEWS = [
  // Trial readouts
  /\b(topline|top-line|pivotal)\b/i,
  /\bphase (1|2|3|i{1,3})\b.{0,50}\b(results|data|met|meets|missed|misses|fails?|succeeds?)\b/i,
  /\b(primary endpoint|interim analysis|maintenance data)\b/i,
  // Regulatory decisions
  /\bFDA\b.{0,40}\b(approv\w*|accepts?|grants?|rejects?|clears?|requests?|feedback)\b/i,
  /\b(complete response letter|CRL|clinical hold|advisory committee|regulatory update|accelerated approval)\b/i,
  // Financings
  /\b(offering|convertible (senior )?notes|private placement|registered direct|at-the-market)\b/i,
  // Deals
  /\b(acquires?|acquisition|merger|to be acquired|takeover|licens(e|ing) (deal|agreement)|collaboration (agreement|deal))\b/i,
  // Leadership and restructuring
  /\b(appoints?|names?|hires?)\b.{0,40}\b(CEO|chief executive)\b/i,
  /\b(CEO|chief executive)\b.{0,30}\b(resigns?|steps down|departs?|to retire|transition)\b/i,
  /\b(layoffs?|restructuring|workforce reduction|delist\w*|reverse (stock )?split|bankruptcy|discontinu\w*)\b/i,
  // Big moves usually follow one of the above
  /\b(surges?|soars?|plunges?|tumbles?|craters?|skyrockets?|rockets?|collapses?)\b/i
];

const isMaterialNews = (title) => MATERIAL_NEWS.some(re => re.test(title || ''));

// Material headlines published after the profile's review date. Carried forward between
// runs (news lists only keep the latest few items) until the profile's `reviewed` date moves
// past them, so review-queue.js can list them.
function updateMaterialNews(stock, previous, reviewed) {
  if (!reviewed) return [];
  const isNew = (n) => (n.date || '').slice(0, 10) > reviewed;
  const found = [...(previous?.materialNews || []), ...(stock.news || []).filter(n => isMaterialNews(n.title))]
    .filter(isNew);
  const byUrl = new Map(found.map(n => [n.url, { title: n.title, source: n.source, date: n.date, url: n.url }]));
  return [...byUrl.values()].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 10);
}

// Google News titles end with " - <source>", which the pages already show separately
function cleanNewsTitle(item) {
  const suffix = ` - ${item.source}`;
  const title = item.title || '';
  return title.toLowerCase().endsWith(suffix.toLowerCase()) ? title.slice(0, -suffix.length).trim() : title;
}

// Combine news from multiple sources
async function getNews(symbol, company) {
  try {
    const yahooNews = await getYahooNews(symbol);
    const googleNews = await getGoogleNews(company);
    const allNews = [...yahooNews, ...googleNews].filter(item => !isLowValueNews(item));

    if (allNews.length === 0) {
      console.warn(`⚠️  No news found for ${symbol}`);
      return [];
    }

    // Remove duplicates and sort by date (newest first)
    const uniqueNews = Array.from(new Map(allNews.map(item => [item.title, item])).values());
    uniqueNews.sort((a, b) => new Date(b.date) - new Date(a.date));

    // Profile pages list up to 6; the homepage feed uses the first 3
    const topNews = uniqueNews.slice(0, 6);
    console.log(`✓ Fetched ${topNews.length} articles from Yahoo Finance & Google News for ${symbol}`);
    if (topNews.length > 0) {
      console.log(`  Latest: ${topNews[0].title} (${topNews[0].date})`);
    }

    return topNews;
  } catch (err) {
    console.warn(`⚠️  Error fetching news for ${symbol}: ${err.message}`);
    return [];
  }
}

// Round to 2 decimals, passing null/undefined through as null
const round2 = (n) => (n == null ? null : parseFloat(n.toFixed(2)));
// 4 significant digits is plenty for chart points and keeps the files small
const round4 = (n) => (n == null ? null : parseFloat(n.toPrecision(4)));

// Return periods shown on the dashboard. Each maps a field name to the date the
// return is measured from; 1D comes straight from the quote.
const RETURN_PERIODS = {
  fiveDay: (now) => daysAgo(now, 7),  // 7 calendar days covers 5 trading days
  oneMonth: (now) => monthsAgo(now, 1),
  sixMonth: (now) => monthsAgo(now, 6),
  ytd: (now) => new Date(now.getFullYear() - 1, 11, 31),  // last close of prior year
  oneYear: (now) => monthsAgo(now, 12),
  threeYear: (now) => monthsAgo(now, 36),
  fiveYear: (now) => monthsAgo(now, 60),
  tenYear: (now) => monthsAgo(now, 120)
};

function daysAgo(now, n) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d;
}

function monthsAgo(now, n) {
  const d = new Date(now);
  d.setMonth(d.getMonth() - n);
  return d;
}

// Fetch returns from Yahoo Finance for 1D plus every period in RETURN_PERIODS.
// Also returns the daily close history (oldest → newest) used for charts.
async function getReturns(symbol, quote, currentPrice, extraTargets = {}) {
  // null means "unavailable" (rendered as —), distinct from a real 0% return
  const returns = { oneDay: round2(quote.regularMarketChangePercent) };
  for (const field of Object.keys(RETURN_PERIODS)) returns[field] = null;
  let history = null;

  try {
    const now = new Date();
    const targets = {
      ...Object.fromEntries(Object.entries(RETURN_PERIODS).map(([field, getDate]) => [field, getDate(now)])),
      ...extraTargets
    };
    // Fetch a little before the oldest target so there's a close on or before it
    const historyStart = daysAgo(new Date(Math.min(...Object.values(targets))), 10);
    const historicalData = await getHistoricalData(symbol, historyStart);

    if (historicalData && historicalData.length > 0) {
      // Sort oldest → newest
      const sorted = historicalData
        .filter(q => q.close != null)
        .sort((a, b) => new Date(a.date) - new Date(b.date));

      // Most recent close on or before the target date. Returns null when the stock's
      // history doesn't reach back that far (e.g. a recent IPO), rather than silently
      // measuring from the first trading day.
      const closeAt = (target) => {
        const q = [...sorted].reverse().find(q => new Date(q.date) <= target);
        return q ? q.close : null;
      };

      for (const [field, target] of Object.entries(targets)) {
        const pastClose = closeAt(target);
        if (pastClose) returns[field] = round2(((currentPrice - pastClose) / pastClose) * 100);
      }
      history = sorted.map(q => [new Date(q.date).toISOString().slice(0, 10), round4(q.close)]);
    }

    const fmt = (v) => (v == null ? '—' : `${v}%`);
    console.log(`    1D: ${fmt(returns.oneDay)} | 5D: ${fmt(returns.fiveDay)} | 1M: ${fmt(returns.oneMonth)} | 6M: ${fmt(returns.sixMonth)} | YTD: ${fmt(returns.ytd)} | 1Y: ${fmt(returns.oneYear)} | 3Y: ${fmt(returns.threeYear)} | 5Y: ${fmt(returns.fiveYear)} | 10Y: ${fmt(returns.tenYear)}`);
  } catch (err) {
    console.warn(`⚠️  Error fetching returns for ${symbol}: ${err.message}`);
  }
  return { returns, history };
}

// Hand-entered cash figures (from the 10-Q) for companies where Yahoo's balance sheet
// is incomplete. Used only while at least as recent as Yahoo's latest quarter —
// update the amount and asOf date each quarter.
const cashOverrides = {
  IOVA: { amount: 304e6, asOf: '2026-06-30' },   // company-reported ~$304M; Yahoo has only $110.8M cash & equivalents
  PRME: { amount: 108.8e6, asOf: '2026-06-30' }  // Yahoo omits Prime's marketable securities
};

const fxRates = {};

// USD per unit of `currency`, e.g. EUR → ~1.14. Null if the rate can't be fetched.
async function getUsdRate(currency) {
  if (currency === 'USD') return 1;
  if (!(currency in fxRates)) {
    try {
      const fx = await yahooFinance.quote(`${currency}USD=X`);
      fxRates[currency] = fx?.regularMarketPrice ?? null;
    } catch (err) {
      console.warn(`    ⚠️  Could not fetch ${currency}/USD rate: ${err.message}`);
      fxRates[currency] = null;
    }
  }
  return fxRates[currency];
}

// Cash and burn from Yahoo's quarterly statements:
// - cash = cash, equivalents & short-term investments + long-term marketable securities
//   (excludes strategic equity stakes), matching what companies report in earnings releases
// - burn = latest quarter's operating cash outflow ÷ 3 (actual cash spent, unlike net loss
//   which includes non-cash items like stock comp and warrant revaluations)
async function getFinancials(symbol, currency) {
  const result = { cashPosition: null, cashAsOf: null, monthlyBurn: null, cashFlowPositive: false };

  try {
    const rows = await withRetry(() => yahooFinance.fundamentalsTimeSeries(symbol, {
      period1: daysAgo(new Date(), 400),
      type: 'quarterly',
      module: 'all'
    }));
    const latest = (field) => [...rows].reverse().find(r => r[field] != null);
    const fx = await getUsdRate(currency || 'USD');

    const bs = latest('cashCashEquivalentsAndShortTermInvestments');
    if (bs && fx) {
      const longTerm = bs.investmentinFinancialAssets ?? bs.investmentsAndAdvances ?? 0;
      result.cashPosition = (bs.cashCashEquivalentsAndShortTermInvestments + longTerm) * fx;
      result.cashAsOf = new Date(bs.date).toISOString().slice(0, 10);
    }

    const cf = latest('operatingCashFlow');
    if (cf && fx) {
      if (cf.operatingCashFlow < 0) result.monthlyBurn = (-cf.operatingCashFlow * fx) / 3;
      else result.cashFlowPositive = true;
    }
  } catch (err) {
    console.warn(`    ⚠️  Could not fetch financials for ${symbol}: ${err.message}`);
  }

  const override = cashOverrides[symbol];
  if (override && (!result.cashAsOf || override.asOf >= result.cashAsOf)) {
    result.cashPosition = override.amount;
    result.cashAsOf = override.asOf;
  } else if (override) {
    // Yahoo now has a newer quarter than the hand-entered figure. Yahoo's number is used,
    // but it was incomplete for this company last time — flag it so the override gets
    // refreshed from the new 10-Q (check-freshness.js fails the run on this).
    result.cashOverrideSuperseded = { overrideAsOf: override.asOf, yahooAsOf: result.cashAsOf };
    console.warn(`    ⚠️  cashOverrides.${symbol} (as of ${override.asOf}) is older than Yahoo's ${result.cashAsOf} — update it from the latest 10-Q`);
  }

  const m = (v) => (v == null ? '—' : `$${(v / 1e6).toFixed(1)}M`);
  console.log(`    Cash: ${m(result.cashPosition)} (as of ${result.cashAsOf ?? '—'}) | Burn: ${result.cashFlowPositive ? 'cash-flow positive' : `${m(result.monthlyBurn)}/mo`}`);
  return result;
}

// Company description, leadership and insider trades (Form 4) from Yahoo
async function getCompanyInfo(symbol) {
  const summary = await withRetry(() => yahooFinance.quoteSummary(symbol, { modules: ['assetProfile', 'insiderTransactions', 'calendarEvents'] }));
  const ap = summary.assetProfile || {};
  return {
    company: {
      summary: ap.longBusinessSummary || null,
      city: ap.city || null,
      state: ap.state || null,
      country: ap.country || null,
      employees: ap.fullTimeEmployees || null,
      website: ap.website || null,
      officers: (ap.companyOfficers || []).slice(0, 5).map(o => ({
        name: cleanOfficerName(o.name),
        title: o.title
      }))
    },
    insiders: parseInsiders(summary.insiderTransactions?.transactions),
    nextEarnings: parseNextEarnings(summary.calendarEvents?.earnings)
  };
}

// Next scheduled earnings date, or null if Yahoo only has one that's already passed
function parseNextEarnings(earnings) {
  const today = new Date().toISOString().slice(0, 10);
  const date = (earnings?.earningsDate || [])
    .map(d => new Date(d).toISOString().slice(0, 10))
    .find(d => d >= today);
  return date ? { date, estimated: Boolean(earnings.isEarningsDateEstimate) } : null;
}

const cleanOfficerName = (name) => String(name || '').replace(/^(Mr|Ms|Mrs|Miss)\.?\s+/, '').replace(/\s+/g, ' ').trim();

// Form 4 transactions, newest first. Rows without a transaction description are
// holdings reports rather than trades, so they're skipped.
function parseInsiders(transactions) {
  return (transactions || [])
    .filter(t => t.transactionText && t.startDate)
    .sort((a, b) => new Date(b.startDate) - new Date(a.startDate))
    .slice(0, 20)
    .map(t => ({
      name: formatInsiderName(t.filerName),
      relation: formatRelation(t.filerRelation),
      date: new Date(t.startDate).toISOString().slice(0, 10),
      type: classifyTransaction(t.transactionText),
      shares: t.shares ?? null,
      value: t.value || null
    }));
}

function classifyTransaction(text) {
  if (/purchase/i.test(text)) return 'BUY';
  if (/sale/i.test(text)) return 'SELL';
  if (/award|grant/i.test(text)) return 'AWARD';
  if (/exercise|conversion/i.test(text)) return 'EXERCISE';
  if (/gift/i.test(text)) return 'GIFT';
  return 'OTHER';
}

const ENTITY_WORDS = /\b(L\.?L\.?C\.?|L\.?P\.?|INC\.?|LTD\.?|PLC|FUND|CAPITAL|INVESTMENTS?|INVESTORS|PARTNERS|VENTURES?|MANAGEMENT|ADVISORS|HOLDINGS|TRUST|COOPERATIEF|GROUP|FOUNDATION)\b/i;
const NAME_SUFFIXES = { JR: 'Jr.', SR: 'Sr.', II: 'II', III: 'III', IV: 'IV' };

const titleWord = (w) => w.toLowerCase().replace(/(^|[-'])([a-z])/g, (m, p, c) => p + c.toUpperCase());

// Yahoo gives filer names as "LAST FIRST MIDDLE" in capitals; entities are left in order
function formatInsiderName(raw) {
  const name = String(raw || '').trim().replace(/\s+/g, ' ');
  if (ENTITY_WORDS.test(name) || /^FMR\b/.test(name)) {
    // Keep short tokens like "RA", "GV", "LLC", "L.P." in capitals
    return name.split(' ').map(w => (w.replace(/[.,]/g, '').length <= 3 ? w : titleWord(w))).join(' ');
  }
  const parts = name.split(' ');
  const suffixes = [];
  while (parts.length > 2 && NAME_SUFFIXES[parts[parts.length - 1].replace(/\./g, '')]) {
    suffixes.unshift(NAME_SUFFIXES[parts.pop().replace(/\./g, '')]);
  }
  const [last, ...rest] = parts;
  return [...rest.map(titleWord), titleWord(last), ...suffixes].join(' ');
}

const formatRelation = (rel) => String(rel || '')
  .replace(/Beneficial Owner of more than 10% of a Class of Security/i, '10% Owner')
  .replace(/ and /g, ', ');

// Put arrays of plain numbers (sparkline points) on one line instead of one number per line
const compactNumberArrays = (json) => json.replace(/\[\s*(-?[\d.e+-]+(?:,\s*-?[\d.e+-]+)*)\s*\]/g, (m, nums) => `[${nums.replace(/\s+/g, '')}]`);

// Summary + page link per theme, for the homepage's theme panel
function themeInfo() {
  return Object.fromEntries(UNIVERSE.themes.map(theme => {
    const file = `${THEME_DIR}/${themeSlug(theme)}.json`;
    const content = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
    return [theme, { summary: content?.summary || null, url: `${THEME_PAGES_DIR}/${themeSlug(theme)}.html` }];
  }));
}

// Previous run's data, so a ticker whose fetch fails keeps its last good values
// (flagged stale) instead of disappearing
function readPreviousData() {
  try {
    return JSON.parse(fs.readFileSync(MARKET_FILE, 'utf8'));
  } catch (err) {
    console.warn(`⚠️  Could not read ${MARKET_FILE}: ${err.message}`);
    return {};
  }
}

const HISTORY_DIR = 'data/history';

// One [date, close] row per line, so each day's commit only adds/removes a couple of lines
function writeHistory(symbol, rows) {
  fs.mkdirSync(HISTORY_DIR, { recursive: true });
  fs.writeFileSync(`${HISTORY_DIR}/${symbol.toLowerCase()}.json`, `[\n${rows.map(r => JSON.stringify(r)).join(',\n')}\n]\n`);
}

function readHistory(symbol) {
  const file = `${HISTORY_DIR}/${symbol.toLowerCase()}.json`;
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : [];
}

// Evenly spaced subset of `rows` (always keeping the last row), at most `max` points
function downsample(rows, max) {
  if (rows.length <= max) return rows;
  const step = (rows.length - 1) / (max - 1);
  return Array.from({ length: max }, (_, i) => rows[Math.round(i * step)]);
}

// Homepage sparklines: closes since each period's start date, ending at the current price.
// 1D has no intraday data, so the homepage uses the 5D line for it.
function sparklines(history, price) {
  if (!history.length) return null;
  const now = new Date();
  const out = {};
  for (const [field, getStart] of Object.entries(RETURN_PERIODS)) {
    const start = getStart(now).toISOString().slice(0, 10);
    if (history[0][0] > start) continue;  // history doesn't reach back that far
    const rows = history.filter(r => r[0] >= start);
    out[field] = [...downsample(rows, 40).map(r => r[1]), price].filter(v => v != null);
  }
  return out;
}

// Profile chart: daily closes for the last year, weekly beyond that
function chartSeries(history) {
  const yearAgo = monthsAgo(new Date(), 12).toISOString().slice(0, 10);
  return {
    daily: history.filter(r => r[0] >= yearAgo),
    weekly: history.filter((r, i) => r[0] < yearAgo && i % 5 === 0)
  };
}

function readProfile(symbol) {
  const file = `${PROFILE_DIR}/${symbol.toLowerCase()}.json`;
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
}

async function buildStockData(symbol, previous) {
  const info = STOCK_INFO[symbol];
  const quote = await withRetry(() => yahooFinance.quote(symbol));
  if (quote?.regularMarketPrice == null) throw new Error('no price in quote');

  const news = await getNews(symbol, info.name);
  // Price move since the editorial profile was last reviewed (for review-queue.js)
  const reviewed = readProfile(symbol)?.reviewed;
  const extraTargets = reviewed ? { sinceReviewed: new Date(`${reviewed}T23:59:59Z`) } : {};
  const { returns, history } = await getReturns(symbol, quote, quote.regularMarketPrice, extraTargets);
  if (history && history.length) writeHistory(symbol, history);
  const financials = await getFinancials(symbol, quote.financialCurrency);

  // Company info changes rarely; reuse the previous copy if this fetch fails
  let companyInfo;
  try {
    companyInfo = await getCompanyInfo(symbol);
  } catch (err) {
    console.warn(`    ⚠️  Could not fetch company info for ${symbol}: ${err.message}`);
    companyInfo = { company: previous?.company || {}, insiders: previous?.insiders || [], nextEarnings: previous?.nextEarnings || null };
  }

  return {
    symbol,
    name: info.name,
    themes: info.themes,
    price: round2(quote.regularMarketPrice),
    change: quote.regularMarketPreviousClose != null ? round2(quote.regularMarketPrice - quote.regularMarketPreviousClose) : null,
    changePercent: round2(quote.regularMarketChangePercent ?? null),
    marketCap: quote.marketCap ?? null,
    updatedAt: new Date().toISOString(),
    ...financials,
    ...returns,
    ...companyInfo,
    news
  };
}

async function updateAll() {
  const stockData = {};
  const previousData = readPreviousData();

  // --render-only rebuilds the HTML from the last run's data without fetching anything,
  // for iterating on templates: `node update-stocks.js --render-only`
  const renderOnly = process.argv.includes('--render-only');
  if (renderOnly) console.log('Render-only: using data/market.json, no fetching');
  else console.log('Fetching stock data...');
  for (const symbol of renderOnly ? [] : STOCKS) {
    console.log(`  ${symbol}...`);
    try {
      stockData[symbol] = await buildStockData(symbol, previousData[symbol]);
    } catch (err) {
      console.warn(`  Failed to fetch ${symbol}: ${err.message}`);
      const prev = previousData[symbol];
      if (prev) {
        console.warn(`  Keeping last good data for ${symbol} (marked stale)`);
        stockData[symbol] = {
          ...prev,
          name: STOCK_INFO[symbol].name,
          themes: STOCK_INFO[symbol].themes,
          stale: true,
          staleSince: prev.staleSince || prev.updatedAt || null
        };
      }
    }
  }

  if (renderOnly) {
    Object.assign(stockData, previousData);
  }
  for (const d of Object.values(stockData)) {
    d.news = (d.news || []).map(n => ({ ...n, title: cleanNewsTitle(n) }));
    d.materialNews = updateMaterialNews(d, previousData[d.symbol], readProfile(d.symbol)?.reviewed);
  }
  if (!renderOnly) {
    // Full data (company info, insiders, all news) for the next run and for profile pages
    fs.writeFileSync(MARKET_FILE, JSON.stringify(stockData, null, 2) + '\n');
    console.log(`\nWrote ${MARKET_FILE}`);
  }

  // Homepage gets a lighter copy: no company details or insider tables, 3 news items
  const coveredSymbols = new Set(STOCKS.filter(s => readProfile(s)));
  const homepageData = Object.fromEntries(Object.entries(stockData).map(([symbol, d]) => {
    const { company, insiders, news, sinceReviewed, cashOverrideSuperseded, materialNews, ...rest } = d;
    return [symbol, { ...rest, covered: coveredSymbols.has(symbol), news: (news || []).slice(0, 3), spark: sparklines(readHistory(symbol), d.price) }];
  }));
  console.log('Updating index.html...');
  let indexHTML = fs.readFileSync('index.html', 'utf8');
  const indent = (json) => json.replace(/^/gm, '      ').trim();
  indexHTML = indexHTML
    .replace(/const demoData = \{[\s\S]*?^\s*\};/m, () => `const demoData = ${indent(compactNumberArrays(JSON.stringify(homepageData, null, 2)))};`)
    .replace(/const THEMES = \[[^\]]*\];/, `const THEMES = ${JSON.stringify(UNIVERSE.themes)};`)
    .replace(/const THEME_INFO = [\s\S]*?; \/\/ end THEME_INFO/, `const THEME_INFO = ${JSON.stringify(themeInfo())}; // end THEME_INFO`)
    // Shared site navigation, footer links and their CSS (from templates/site.js)
    .replace(/<!-- SITE_NAV -->[\s\S]*?<!-- \/SITE_NAV -->/, () => `<!-- SITE_NAV -->\n${renderNav('', UNIVERSE.themes, 'dashboard')}\n  <!-- /SITE_NAV -->`)
    .replace(/<!-- SITE_FOOTER -->[\s\S]*?<!-- \/SITE_FOOTER -->/, () => `<!-- SITE_FOOTER -->\n${renderFooterLinks('', UNIVERSE.themes)}\n    <!-- /SITE_FOOTER -->`)
    .replace(/\/\* SITE_NAV_CSS \*\/[\s\S]*?\/\* \/SITE_NAV_CSS \*\//, () => `/* SITE_NAV_CSS */${NAV_CSS.replace(/^/gm, '    ')}    /* /SITE_NAV_CSS */`)
    // SEO head tags and crawlable static copies of the stock list and news feed
    .replace(/<!-- SEO_HEAD -->[\s\S]*?<!-- \/SEO_HEAD -->/, () => `<!-- SEO_HEAD -->\n${renderHomeHead(SITE)}\n  <!-- /SEO_HEAD -->`)
    .replace(/<!-- STATIC_STOCKS -->[\s\S]*?<!-- \/STATIC_STOCKS -->/, () => `<!-- STATIC_STOCKS -->${renderStaticStocks(Object.values(stockData))}<!-- /STATIC_STOCKS -->`)
    .replace(/<!-- STATIC_NEWS -->[\s\S]*?<!-- \/STATIC_NEWS -->/, () => `<!-- STATIC_NEWS -->${renderStaticNews(Object.values(stockData))}<!-- /STATIC_NEWS -->`);
  fs.writeFileSync('index.html', indexHTML);

  // Profile pages are regenerated in full from the template
  fs.mkdirSync(PAGES_DIR, { recursive: true });
  for (const symbol of STOCKS) {
    if (!stockData[symbol]) continue;
    fs.writeFileSync(`${PAGES_DIR}/${symbol.toLowerCase()}.html`, renderProfile(stockData[symbol], readProfile(symbol), UNIVERSE.themes, SITE.url, chartSeries(readHistory(symbol))));
  }
  console.log(`Rendered ${Object.keys(stockData).length} profile pages (${coveredSymbols.size} covered, ${Object.keys(stockData).length - coveredSymbols.size} tracked)`);

  // Theme pages: science background from data/themes + live data for the theme's stocks
  fs.mkdirSync(THEME_PAGES_DIR, { recursive: true });
  const profiles = Object.fromEntries(STOCKS.map(s => [s, readProfile(s)]));
  for (const theme of UNIVERSE.themes) {
    const file = `${THEME_DIR}/${themeSlug(theme)}.json`;
    const content = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : null;
    const members = STOCKS.filter(s => stockData[s] && STOCK_INFO[s].themes.includes(theme)).map(s => stockData[s]);
    fs.writeFileSync(`${THEME_PAGES_DIR}/${themeSlug(theme)}.html`, renderTheme(theme, content, members, profiles, UNIVERSE.themes, SITE.url));
  }
  console.log(`Rendered ${UNIVERSE.themes.length} theme pages`);

  fs.writeFileSync('calendar.html', renderCalendar(STOCKS.filter(s => stockData[s]).map(s => stockData[s]), profiles, UNIVERSE.themes, SITE.url));
  console.log('Rendered calendar.html');

  // sitemap.xml + robots.txt so search engines can find every page
  const today = new Date().toISOString().slice(0, 10);
  const pages = ['', 'calendar.html',
    ...UNIVERSE.themes.map(t => `${THEME_PAGES_DIR}/${themeSlug(t)}.html`),
    ...STOCKS.filter(s => stockData[s]).map(s => `${PAGES_DIR}/${s.toLowerCase()}.html`)];
  fs.writeFileSync('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(p => `  <url><loc>${SITE.url}${p}</loc><lastmod>${today}</lastmod><changefreq>daily</changefreq></url>`).join('\n')}
</urlset>
`);
  fs.writeFileSync('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${SITE.url}sitemap.xml\n`);
  console.log(`Wrote sitemap.xml (${pages.length} pages) and robots.txt`);

  // Remove generated pages for stocks no longer in the universe
  const current = new Set(STOCKS.map(s => `${s.toLowerCase()}.html`));
  for (const file of fs.readdirSync(PAGES_DIR)) {
    if (!file.endsWith('.html') || current.has(file)) continue;
    if (fs.readFileSync(`${PAGES_DIR}/${file}`, 'utf8').includes(GENERATED_MARKER)) {
      fs.unlinkSync(`${PAGES_DIR}/${file}`);
      console.log(`  Removed ${PAGES_DIR}/${file} (no longer in data/universe.json)`);
    }
  }

  console.log('\n✅ Stock data updated!');
  for (const symbol of STOCKS) {
    const d = stockData[symbol];
    if (d) console.log(`${symbol}: $${d.price} ${d.changePercent >= 0 ? '+' : ''}${d.changePercent}% | YTD: ${d.ytd == null ? '—' : d.ytd + '%'}${d.stale ? ' (STALE)' : ''}`);
    else console.log(`${symbol}: MISSING (fetch failed and no previous data)`);
  }
}

// Run
updateAll().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
