// Renders beaten-down.html: the curated "Beaten Down, Not Out" list from data/beaten-down.json.
// Automatic metrics (drawdown from peak, bounce off the 52-week low, return since added,
// cash vs market cap) sit next to a hand-written thesis for each stock. Also renders the
// homepage strip and the profile-page notice that link to it.

const {
  formatMoney, pctColor, formatDate, runwayText, escapeHtml, stripTags, CSS, DISCLAIMER
} = require('./profile');
const { NAV_CSS, renderNav, renderFooterLinks, seoTags } = require('./site');

const PAGE = 'beaten-down.html';

const THESIS_PARTS = [
  ['whyItFell', 'Why it fell'],
  ['whyItCouldRecover', 'Why it could recover'],
  ['whatBreaksIt', 'What would break the thesis']
];

const BEATEN_CSS = `
.bd-table td.num strong {
  color: #dc2626;
}

.thesis-card {
  border-top: 1px solid #e5e7eb;
  padding-top: 1.25rem;
  margin-top: 1.25rem;
}

.thesis-card:first-of-type {
  border-top: none;
  margin-top: 0;
  padding-top: 0;
}

.thesis-card h3 {
  margin-bottom: 0.25rem;
}

.thesis-card h3 a {
  color: inherit;
  text-decoration: none;
}

.thesis-card h4 {
  font-size: 0.9rem;
  color: #374151;
  margin: 0.9rem 0 0.3rem;
}

.thesis-pending {
  color: #6b7280;
  font-style: italic;
}
`;

const signed = (v) => (v == null ? '—' : `${v > 0 ? '+' : ''}${v}%`);
const cashToCap = (s) => (s.cashPosition && s.marketCap ? `${Math.round((s.cashPosition / s.marketCap) * 100)}%` : '—');
const hasThesis = (t) => THESIS_PARTS.some(([key]) => t?.[key]);

// entries: [{ symbol, added, thesis, stock, stats }] with stock/stats already resolved
function renderBeatenDown(list, entries, themes = [], siteUrl = null) {
  const description = stripTags(list.intro).slice(0, 300);
  const byDrawdown = [...entries].sort((a, b) => (a.stats?.fromPeak ?? 0) - (b.stats?.fromPeak ?? 0));

  const rows = byDrawdown.map(({ stock: s, stats, added }) => `          <tr>
            <td><a href="stocks/${s.symbol.toLowerCase()}.html">${s.symbol}</a></td>
            <td>${escapeHtml(s.name)}</td>
            <td class="num">${s.price == null ? '—' : `$${s.price.toFixed(2)}`}</td>
            <td class="num"><strong>${signed(stats?.fromPeak)}</strong>${stats?.peakDate ? `<div class="item-meta">high ${formatDate(stats.peakDate, { month: 'short', year: 'numeric' })}</div>` : ''}</td>
            <td class="num" style="color: ${pctColor(stats?.fromLow)}">${signed(stats?.fromLow)}</td>
            <td class="num" style="color: ${pctColor(stats?.sinceAdded)}">${signed(stats?.sinceAdded)}<div class="item-meta">${formatDate(added)}</div></td>
            <td class="num">${formatMoney(s.marketCap)}</td>
            <td class="num">${cashToCap(s)}</td>
            <td class="num">${s.cashFlowPositive && !s.monthlyBurn ? 'No burn' : runwayText(s)}</td>
          </tr>`).join('\n');

  const cards = byDrawdown.map(({ stock: s, stats, thesis }) => `      <div class="thesis-card" id="${s.symbol.toLowerCase()}">
        <h3><a href="stocks/${s.symbol.toLowerCase()}.html">${escapeHtml(s.name)} (${s.symbol})</a></h3>
        <div class="item-meta">${signed(stats?.fromPeak)} from its high · ${signed(stats?.fromLow)} off its 52-week low · cash ${cashToCap(s)} of market cap</div>
${hasThesis(thesis)
    ? THESIS_PARTS.filter(([key]) => thesis[key]).map(([key, label]) => `        <h4>${label}</h4>\n        <p class="para">${thesis[key]}</p>`).join('\n')
    : '        <p class="para thesis-pending">Thesis coming soon.</p>'}
      </div>`).join('\n');

  return `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(list.title)}: Beaten-Down Biotech Stocks | Life Science Investor</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta property="og:title" content="${escapeHtml(list.title)} — Life Science Investor">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:type" content="article">
${seoTags(siteUrl, PAGE)}
  <style>
${(CSS + NAV_CSS + BEATEN_CSS).replace(/^/gm, '    ').replace(/^\s+$/gm, '')}
  </style>
</head>

<body>
  <!-- Generated by update-stocks.js from data/beaten-down.json and live market data. Do not edit by hand. -->
${renderNav('', themes, 'beaten-down')}

  <header>
    <div>
      <h1>${escapeHtml(list.title)}</h1>
      <div>${entries.length} stock${entries.length === 1 ? '' : 's'}</div>
    </div>
  </header>

  <div class="container">

    <div class="section">
      <p class="para" style="margin-bottom: 0;">${list.intro}</p>
    </div>

    <div class="section">
      <h2>The List</h2>
      <div style="overflow-x: auto;">
      <table class="bd-table">
        <thead>
          <tr>
            <th>Ticker</th>
            <th>Company</th>
            <th class="num">Price</th>
            <th class="num">From high</th>
            <th class="num">Off 52W low</th>
            <th class="num">Since added</th>
            <th class="num">Mkt Cap</th>
            <th class="num">Cash ÷ Cap</th>
            <th class="num">Runway</th>
          </tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
      </div>
      <p class="note">Sorted by distance from high. "From high" compares today's price with the highest close in the last ~10 years. Cash ÷ Cap is cash and investments as a share of market value; a high figure means the market values the pipeline at little more than the cash. Runway = cash ÷ latest quarter's operating cash burn.</p>
    </div>

    <div class="section">
      <h2>The Theses</h2>
${cards}
      <div class="meta-line">List last reviewed ${formatDate(list.reviewed)}. Opinion, not a recommendation: these stocks are high-risk and many clinical-stage companies never recover.</div>
    </div>

  </div>

  <footer class="disclaimer">
${renderFooterLinks('', themes)}
    <p>${DISCLAIMER}</p>
  </footer>

</body>

</html>
`;
}

// Homepage strip: one compact link per stock, biggest drawdown first
function renderBeatenDownStrip(list, entries) {
  const sorted = [...entries].sort((a, b) => (a.stats?.fromPeak ?? 0) - (b.stats?.fromPeak ?? 0));
  return `<section class="beaten-strip" aria-label="${escapeHtml(list.title)}">
      <div class="beaten-strip-head"><a href="${PAGE}">${escapeHtml(list.title)}</a> <span>Far below their highs, thesis intact →</span></div>
      <div class="beaten-strip-items">
${sorted.map(({ stock: s, stats }) => `        <a class="beaten-chip" href="${PAGE}#${s.symbol.toLowerCase()}"><strong>${s.symbol}</strong> <span>${signed(stats?.fromPeak)}</span></a>`).join('\n')}
      </div>
    </section>`;
}

// Notice at the top of a listed stock's profile page
function renderBeatenDownNotice(list, stats, symbol) {
  const from = stats?.fromPeak != null && stats.fromPeak < 0
    ? ` It trades ${Math.abs(stats.fromPeak)}% below its ${stats.peakDate ? formatDate(stats.peakDate, { month: 'short', year: 'numeric' }) + ' ' : ''}high.`
    : '';
  return `    <div class="notice notice-beaten">On our <a href="../${PAGE}#${symbol.toLowerCase()}">${escapeHtml(list.title)}</a> list of beaten-down stocks with an intact thesis.${from}</div>`;
}

module.exports = { renderBeatenDown, renderBeatenDownStrip, renderBeatenDownNotice, BEATEN_CSS, PAGE };
