// Renders a theme page (themes/<slug>.html): science background from data/themes/<slug>.json
// plus live data for every stock in the theme — a comparison table, upcoming catalysts
// (from covered stocks' profiles), upcoming earnings and combined news.

const { themeSlug } = require('../lib/themes');
const { parseTimingEnd, isPast } = require('../lib/catalyst-timing');
const {
  formatMoney, formatPct, pctColor, formatDate, runwayText, escapeHtml, stripTags, CSS, DISCLAIMER
} = require('./profile');
const { NAV_CSS, renderNav, renderFooterLinks, seoTags } = require('./site');

function renderTheme(theme, content, stocks, profiles, themes = [], siteUrl = null) {
  const slug = themeSlug(theme);
  const description = stripTags(content?.summary || `${theme} stocks: science background, company comparison, catalysts and news.`).slice(0, 300);
  const byReturn = [...stocks].sort((a, b) => (b.ytd ?? -Infinity) - (a.ytd ?? -Infinity));

  const science = content
    ? `    <div class="section science">
      <h2>The Science</h2>
${content.sections.map(sec => `      <h3>${sec.heading}</h3>\n      ${sec.body}`).join('\n')}
      <div class="meta-line">Background last reviewed ${formatDate(content.reviewed)}. General educational content, not a recommendation.</div>
    </div>`
    : '';

  const rows = byReturn.map(s => `          <tr>
            <td><a href="../stocks/${s.symbol.toLowerCase()}.html">${s.symbol}</a></td>
            <td>${escapeHtml(s.name)}${profiles[s.symbol] ? '' : ' <span class="item-meta">(data only)</span>'}</td>
            <td class="num">${s.price == null ? '—' : `$${s.price.toFixed(2)}`}</td>
            <td class="num" style="color: ${pctColor(s.oneDay)}">${formatPct(s.oneDay)}</td>
            <td class="num" style="color: ${pctColor(s.ytd)}">${formatPct(s.ytd)}</td>
            <td class="num" style="color: ${pctColor(s.oneYear)}">${formatPct(s.oneYear)}</td>
            <td class="num">${formatMoney(s.marketCap)}</td>
            <td class="num">${runwayText(s)}</td>
          </tr>`).join('\n');

  // Catalysts from covered stocks that haven't passed, soonest first; undated ones last
  const catalysts = stocks
    .flatMap(s => (profiles[s.symbol]?.catalysts || []).map(c => ({ ...c, symbol: s.symbol, name: s.name })))
    .filter(c => !isPast(c.timing))
    .map(c => ({ ...c, end: parseTimingEnd(c.timing) }))
    .sort((a, b) => (a.end ?? Infinity) - (b.end ?? Infinity));

  const earnings = stocks
    .filter(s => s.nextEarnings)
    .sort((a, b) => a.nextEarnings.date.localeCompare(b.nextEarnings.date));

  const newsByUrl = new Map();
  for (const s of stocks) {
    for (const n of s.news || []) {
      if (!n.url || n.url === '#') continue;
      if (!newsByUrl.has(n.url)) newsByUrl.set(n.url, { ...n, tickers: [] });
      newsByUrl.get(n.url).tickers.push(s.symbol);
    }
  }
  const news = [...newsByUrl.values()].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 15);

  return `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(theme)} Stocks — Science, Catalysts &amp; News | Life Science Investor</title>
  <meta name="description" content="${escapeHtml(description)}">
  <meta property="og:title" content="${escapeHtml(theme)} Stocks — Life Science Investor">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:type" content="article">
${seoTags(siteUrl, `themes/${slug}.html`)}
  <style>
${(CSS + NAV_CSS).replace(/^/gm, '    ').replace(/^\s+$/gm, '')}
  </style>
</head>

<body>
  <!-- Generated by update-stocks.js from data/themes/${slug}.json and live market data. Do not edit by hand. -->
${renderNav('../', themes, 'themes')}

  <header>
    <div>
      <h1>${escapeHtml(theme)}</h1>
      <div>${stocks.length} compan${stocks.length === 1 ? 'y' : 'ies'} tracked</div>
    </div>
  </header>

  <div class="container">

${content ? `    <div class="section">
      <p class="para" style="margin-bottom: 0;">${content.summary}</p>
    </div>

` : ''}${science}

    <div class="section">
      <h2>Companies</h2>
      <div style="overflow-x: auto;">
      <table>
        <thead>
          <tr>
            <th>Ticker</th>
            <th>Company</th>
            <th class="num">Price</th>
            <th class="num">1D</th>
            <th class="num">YTD</th>
            <th class="num">1Y</th>
            <th class="num">Mkt Cap</th>
            <th class="num">Runway</th>
          </tr>
        </thead>
        <tbody>
${rows}
        </tbody>
      </table>
      </div>
      <p class="note">Sorted by year-to-date return. Runway = cash ÷ latest quarter's operating cash burn.</p>
    </div>

    <div class="section">
      <h2>Upcoming Catalysts</h2>
${catalysts.length ? `      <ul class="item-list">
${catalysts.map(c => `        <li><strong>${c.title}</strong> <span class="badge badge-${c.color}">${c.impact}</span>
          <div class="item-meta"><a href="../stocks/${c.symbol.toLowerCase()}.html">${c.symbol}</a> · ${c.timing}</div></li>`).join('\n')}
      </ul>
      <p class="note">From each company's profile; timing reflects company guidance as of the profile's review date.</p>` : '      <p class="note">No upcoming catalysts listed.</p>'}
    </div>

    <div class="section">
      <h2>Upcoming Earnings</h2>
${earnings.length ? `      <ul class="item-list">
${earnings.map(s => `        <li><a href="../stocks/${s.symbol.toLowerCase()}.html">${s.symbol}</a> ${escapeHtml(s.name)}
          <div class="item-meta">${formatDate(s.nextEarnings.date)}${s.nextEarnings.estimated ? ' (estimated)' : ' (confirmed)'}</div></li>`).join('\n')}
      </ul>` : '      <p class="note">No earnings dates scheduled.</p>'}
    </div>

    <div class="section">
      <h2>Latest News</h2>
${news.length ? `      <ul class="item-list">
${news.map(n => `        <li><a href="${escapeHtml(n.url)}" target="_blank" rel="noopener">${escapeHtml(n.title)}</a>
          <div class="item-meta">${n.tickers.join(', ')} · ${escapeHtml(n.source)} · ${formatDate(n.date)}</div></li>`).join('\n')}
      </ul>` : '      <p class="note">No recent news.</p>'}
    </div>

  </div>

  <footer class="disclaimer">
${renderFooterLinks('../', themes)}
    <p>${DISCLAIMER}</p>
  </footer>

</body>

</html>
`;
}

module.exports = { renderTheme, themeSlug };
